#!/usr/bin/with-contenv sh

START_APACHE2=${START_APACHE2:-YES}
START_VSFTPD=${START_VSFTPD:-YES}
CREATE_TESTUSER=${CREATE_TESTUSER:-NO}
WWW_DATA_UID=${WWW_DATA_UID:-33}
WWW_DATA_GID=${WWW_DATA_GID:-33}
SSL=${SSL:-NO}
SSL_KEY=${SSL_KEY:-/etc/ssl/apache2/server.key}
SSL_CERT=${SSL_CERT:-/etc/ssl/apache2/server.pem}

APACHE2_SERVER_NAME=${APACHE2_SERVER_NAME:-localhost}
APACHE2_SERVER_PORT=80

VSFTPD_PASV_ADDRESS=${VSFTPD_PASV_ADDRESS:-localhost}
VSFTPD_PASV_MAX_PORT=${VSFTPD_PASV_MAX_PORT:-21110}
VSFTPD_PASV_MIN_PORT=${VSFTPD_PASV_MIN_PORT:-21100}

mkdir -p /var/www/default

# CONFIGURE APACHE CONF, WWW USER, SSL
if grep -q "\-SERVER_PORT\-" /etc/apache2/httpd.conf; then
    addgroup -g $WWW_DATA_GID www-data
    adduser -G www-data -g "www user" -D -h /var/www -s /sbin/nologin -u $WWW_DATA_UID www-data
    mkdir -p /var/www/webdav /var/lib/apache2 /var/log/apache2
    chown www-data:www-data /var/lib/apache2 /var/log/apache2
    echo "* configure httpd.conf"
    if [ "$SSL" = "YES" ]; then
        APACHE2_SERVER_PORT=443
        sed -i \
            -e "s/#-SSL_OFF-//" \
            /etc/apache2/httpd.conf
        sed -i \
            -e "s#-SSL_KEY-#${SSL_KEY}#" \
            -e "s#-SSL_CERT-#${SSL_CERT}#" \
            /etc/apache2/httpd.conf
    fi
    sed -i \
        -e "s#-SERVER_NAME-#${APACHE2_SERVER_NAME}#" \
        -e "s#-SERVER_PORT-#${APACHE2_SERVER_PORT}#" \
        /etc/apache2/httpd.conf
fi

if [ "$CREATE_TESTUSER" = "YES" ] && [ ! -d "/var/www/testuser/webdav" ]; then
    mkdir -p /var/www/testuser/webdav
    chown www-data:www-data /var/www/testuser/webdav
fi

if [ "$START_APACHE2" = "YES" ]; then
    rm /etc/services.d/apache2/down
fi

# CONFIGURE VSFTPD
if grep -q "\-PASV_ADDRESS\-" /etc/vsftpd/vsftpd.conf; then
    echo "* configure vsftpd.conf"
    if [ "$SSL" = "YES" ]; then
        SERVER_PORT=443
        sed -i \
            -e "s/#-SSL_OFF-//" \
            /etc/vsftpd/vsftpd.conf
        sed -i \
            -e "s#-SSL_KEY-#${SSL_KEY}#" \
            -e "s#-SSL_CERT-#${SSL_CERT}#" \
            /etc/vsftpd/vsftpd.conf
    fi
    sed -i \
        -e "s#-PASV_ADDRESS-#${VSFTPD_PASV_ADDRESS}#" \
        -e "s#-PASV_MAX_PORT-#${VSFTPD_PASV_MAX_PORT}#" \
        -e "s#-PASV_MIN_PORT-#${VSFTPD_PASV_MIN_PORT}#" \
        /etc/vsftpd/vsftpd.conf
fi

if [ "$START_VSFTPD" = "YES" ]; then
    rm /etc/services.d/vsftpd/down
fi
